### ISSUE TITLE
Load microkernel in UEFI mode

### ISSUE THREAD

**Issue by Thomas77777** [puppetlabs/Razor#515]
Hello Razor team, 

I have followed your [installation guide](https://github.com/puppetlabs/razor-server/wiki/Installation#razor-server-setup) in order to deploy OS though PXE. Note that computers where I'm trying to install OS automatically are running in UEFI mode and do not accept Legacy BIOS mode.

In my case : 
1- Razor server installation --> OK 
2- DNSMAQ configuration --> OK 

Extract from my dnsmasq.conf

dhcp-match=IPXEBOOT,175
dhcp-match=X86-64_EFI, option:client-arch, 7 

dhcp-boot=net:IPXEBOOT,bootstrap.ipxe
dhcp-boot=net:X86-64_EFI,ipxe.efi
dhcp-boot=undionly-20140116.kpxe

3- [Prebuilt microkernel](https://s3-us-west-2.amazonaws.com/razor-releases/microkernel-007.tar) downloaded and extracted in razor repository --> OK

4- [udionly.kpxe](http://boot.ipxe.org/undionly.kpxe) and bootstrap.ipxe (generated with http://razor:8150/api/microkernel/bootstrap?nic_max=N) extracted in /var/lib/tftpboot --> OK

5- I have generated the file "ipxe.efi" with the following [website ](https://rom-o-matic.eu/) and moved it to /var/lib/tftpboot. Note that I used to same ipxe script than the script from bootstrap.ipxe to generate the file "ipxe.efi". 

When the computer is on, the file "ipxe.efi" is downloaded and an IP address is returned by the Razor server. The files "initidr0.img" and "vmlinuz0" are sent to the machine though TFTP and ... that's all :(
I cannot interact with the computer and I have the same issue if I switch off and on again.

What am i doing wrong during the installation process?

Thank you in advance for your help. 

Thomas.

**Comment by smcclellan** [comment]
Hi Thomas,

This is the old Razor repository, the new being https://github.com/puppetlabs/razor-server. Please file this ticket at https://tickets.puppetlabs.com/browse/RAZOR so that it can be tracked.

Thanks!
